name: Publish

on:
  release:
    types: [created]

permissions: {}

jobs:
  snapshot:
    name: Snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Build package
        run: pnpm build
      - name: Setup git
        run: git config --global user.email "info@example.com" && git config --global user.name "GitHub Actions"
      - name: Update version
        run: npm version ${{ github.event.release.tag_name }}
      - name: Publish package on NPM 📦
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

